### ISSUE TITLE
.submit-partition-function-jobs.pl.swp is accidentally committed

### ISSUE THREAD

**Issue by rht** [guygurari/syk#1]
The file: https://github.com/guygurari/syk/blob/master/scripts/.submit-partition-function-jobs.pl.swp contains some metadata in it.

I was thinking of making a PR to remove it, I think it would be cleaner if the file is removed in the commit that introduced it via a force-push.

**Comment by guygurari** [comment]
I removed the file with a force-push. Thanks for flagging this!
